; PlatformIO Project Configuration File
; Wemos D1 mini (ESP8266) — traffic light toy

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    arduino-libraries/Servo
